# Site settings
title: Talent Unbound | Galleria, Houston, TX.
tagline: School Reimagined
url: "https://talent-unbound-galleria.github.io/location-website/" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/logo.png # be sure to change this image
facebook:
twitter:
instagram:

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
